services:
  - type: web
    name: preference-analyzer
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8003
    envVars:
      - key: PORT
        value: 8003
